# Generated by Django 6.0.3 on 2026-04-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
