from django.urls import path
from .views import (
    RegisterView,
    MeView,
    SendVerificationCodeView,
    VerifyCodeView,
    PasswordResetRequestView,
    PasswordResetVerifyCodeView,
    PasswordResetConfirmView,
    AdminStatsView,
    AdminUserListView,
    AdminUserDetailView,
    AdminUserDeactivateView,
    AdminListingListView,
    AdminListingDetailView,
    AdminListingDeleteView,
    AdminOrderListView,
    AdminOrderDetailView,
    AdminPaymentListView,
)

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("me/", MeView.as_view(), name="me"),
    path(
        "send-verification-code/",
        SendVerificationCodeView.as_view(),
        name="send-verification-code",
    ),
    path("verify-code/", VerifyCodeView.as_view(), name="verify-code"),
    path("password-reset/request/", PasswordResetRequestView.as_view()),
    path("password-reset/confirm/", PasswordResetConfirmView.as_view()),
    path("password-reset/verify-code/", PasswordResetVerifyCodeView.as_view()),
    path("admin/stats/", AdminStatsView.as_view()),
    path("admin/users/", AdminUserListView.as_view()),
    path("admin/users/<int:pk>/", AdminUserDetailView.as_view()),
    path("admin/users/<int:pk>/deactivate/", AdminUserDeactivateView.as_view()),
    path("admin/listings/", AdminListingListView.as_view()),
    path("admin/listings/<int:pk>/", AdminListingDetailView.as_view()),
    path("admin/listings/<int:pk>/delete/", AdminListingDeleteView.as_view()),
    path("admin/orders/", AdminOrderListView.as_view()),
    path("admin/orders/<int:pk>/", AdminOrderDetailView.as_view()),
    path("admin/payments/", AdminPaymentListView.as_view()),
]
