# Generated by Django 6.0.3 on 2026-04-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_listing_condition_alter_listing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
